config/routes.rb
Rails.application.routes.draw do

  devise_for :members, :controllers => { registrations: "registrations"}
  root "posts#index"

  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  validates :username, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, except: [:index, :show]


  def index
    @posts = Post.all
    @post = Post.new
  end

  def new
    @post = current_member.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_member.posts.build(post_params)

    if @post.save
      redirect_to posts_path
      flash[:notice] = "Post saved"
    else
      flash.now[:notice] = "Error fields missing"
      render :new
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
      flash[:notice] = "Post updated"
    else
      flash.now[:notice] = "Error, try again"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path

  end

  private

  def post_params
    params.require(:post).permit(:title,:body)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

def sign_up_params
  params.require(:member).permit(:username, :email, :password, :password_confirmation)
end

def account_update_params
  params.require(:member).permit(:username, :email, :password, :password_confirmation, :current_password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clubhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "posts/nav"%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>
  <%= f.label :title, class:"form-label" %> <br>
  <%= f.text_field :title, class:"form-control" %>

<br>

  <%= f.label :body, class:"form-label" %> <br>
  <%= f.text_area :body, class:"form-control" %>

<br>
<br>

  <%= f.submit "Make Post", class:"btn btn-primary"  %>
<% end %>

app/views/posts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Clubhouse", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Sign in", new_member_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_member_session_path, method: "delete", class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign up", new_member_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Update user", edit_member_registration_path, class:"nav-link" %>
        </li>
      </ul>
      
    </div>
  </div>
</nav>

app/views/posts/edit.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h2>Edit post:</h2>

<%= render "form", post: @post %>

<%= link_to "Back", posts_path%>

app/views/posts/index.html.erb
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


 <div class="container shadow p-3 mb-5 bg-body rounded w-25"> 
  <% if member_signed_in? %>
  <h2>Welcome User: <%= current_member.username%></h2>
  <% else %>
  <h2>Pls sign in</h2>
  <% end %>
</div>

<div class="spacer"></div>

<div class="row justify-content-center bg-info text-light border">
  <div class="col-4 text-center">
    <div class="index">
      <% @posts.each do |p| %>
        <div class="border mg shadow">
        <% if member_signed_in? %>
          <h3> Username: <%= Member.find(p.member_id).username %></h3>
            <% else %>
          <h3>Sign in to see Username </h3>
        <% end %>
          <p>Title: <%= p.title %></p>
          <p>Text: <%= p.body %></p>
          <p>Show post: <%= link_to "Post", p %> </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-4">
    <%= render "form", post: @post %><br>
  </div>
</div>

app/views/posts/new.html.erb
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<h3>Tweet</h3>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h2> Title: <%= @post.title %></h2>

<h2> Body: <%= @post.body %></h2>

<p>Edit post:<%= link_to "Edit", edit_post_path(@post)%> </p>

<p>Delete post:<%= link_to "Delete", post_path(@post),
 method: "delete",
 data: { confirm: "Delete post" } %></p>

<p> Back to: <%= link_to "index", posts_path %></p>